//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC_Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ASCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ASCResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC_Client.ASCResource", typeof(ASCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select f.*,
        ///	   DATE_FORMAT(f.date_time, &apos;%d.%m.%Y %H:%i:%s&apos;) file_datetime 
        ///from `asc`.dev_files f
        ///where f.dev_id = @p_imei
        ///and f.date_time between @p_date_from and @p_date_to
        ///order by f.file_id desc.
        /// </summary>
        internal static string SQL_DEVFILES {
            get {
                return ResourceManager.GetString("SQL_DEVFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT max(h.date_time) last_heartbeat,
        ///	   max(case when (t.track_type = &apos;deaf&apos; and t.track_status = 1) then 1 else -1 end) deaf, 
        ///       max(case when (t.track_type = &apos;lame&apos; and t.track_status = 1) then 1 else -1 end) lame, 
        ///       max(case when (t.track_type = &apos;track&apos; and t.track_status = 1) then 1 else -1 end) track,
        ///       d.*, 
        ///       p.* 
        ///FROM   asc.dev_info d 
        ///       LEFT JOIN asc.dev_person p 
        ///              ON p.dev_id = d.dev_imei 
        ///                 AND p.history = 1 
        ///       LEFT JOIN asc.dev_track [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_DEVINFO {
            get {
                return ResourceManager.GetString("SQL_DEVINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select d.dev_id,
        ///	   d.loc_type,
        ///	   FORMAT(d.loc_x, 4) loc_x,
        ///	   FORMAT(d.loc_y, 4) loc_y, 
        ///	   DATE_FORMAT(d.date_time, &apos;%d.%m.%Y %H:%i:%s&apos;) loc_datetime from `asc`.dev_location d
        ///where d.dev_id = @p_imei
        ///and d.date_time between @p_date_from and @p_date_to
        ///order by d.loc_id desc.
        /// </summary>
        internal static string SQL_DEVLOCATION {
            get {
                return ResourceManager.GetString("SQL_DEVLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20180203.
        /// </summary>
        internal static string vBuild {
            get {
                return ResourceManager.GetString("vBuild", resourceCulture);
            }
        }
    }
}
